### ISSUE TITLE
rba_panther_family gives NULL

### ISSUE THREAD

**Issue by anulin** [moosa-r/rbioapi#14]
Hello! I was using rba_panther_family("PTHR11937",'tree') and it worked perfectly fine, but now gives NULL for some reason. Also it gives NULL for other families and for rba_panther_family("PTHR11937",'msa')

**Comment by moosa-r** [comment]
Hello.

Thank you for reporting this issue.

I've made minor fixes to reflect the recent changes in PANTHER's API in the past few weeks.
You can reinstall rbioapi with the latest fix using the following commands: (I will submit it to CRAN when some changes accumulate)

````
install.packages("remotes")
remotes::install_github("moosa-r/rbioapi")
````

Hopefully, this will solve your problem.

**Comment by anulin** [comment]
Thank you, it worked
