### ISSUE TITLE
Installation Error: could not find function "cwd"

### ISSUE THREAD

**Issue by avishai987** [moosa-r/rbioapi#15]
Hi, thanks for the nice-looking package.
I tried to install the package  (throught CRAN and Github) but I am getting this error:
`Error: could not find function "cwd" 
Execution halted
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpLK3yuT/file13f3058005337/rbioapi_0.8.0.tar.gz’ had non-zero exit status
`
Thanks!
Session info:

>  setting  value
 version  R version 4.1.3 (2022-03-10)
 os       Ubuntu 20.04.4 LTS
 system   x86_64, linux-gnu
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Etc/UTC
 date     2024-01-10
 rstudio  2022.02.1+461 Prairie Trillium (server)
 pandoc   2.17.1.1 @ /usr/lib/rstudio-server/bin/quarto/bin/ (via rmarkdown)

**Comment by moosa-r** [comment]
Dear @avishai987 

Sorry to hear that.

I tried to install rbioapi on the WSL Ubuntu on my laptop a moment ago, and it installed just fine.
Furthermore, I triggered [this GitHub action](https://github.com/moosa-r/rbioapi/actions/runs/7477401421) that installs the package and performs checks on several R versions and operation systems (please see below). All tests were passed successfully as you can see in the [action logs](https://github.com/moosa-r/rbioapi/actions/runs/7477401421).

R version 4.3.2 on macOS 12.7.2
R version 4.3.2 on Windows Server 2022 10.0.20348
R version 3.6.3 on Windows Server 2022 10.0.20348
R version 4.1.3 on Windows Server 2022 10.0.20348
R version 4.3.2 on Ubuntu 22.04.3
R Under development (unstable) (2024-01-09 r85796) on Ubuntu 22.04.3
R version 4.2.3 on Ubuntu 22.04.3
R version 4.1.3 on Ubuntu 22.04.3
R version 4.0.5 on Ubuntu 22.04.3
R version 3.6.3 on Ubuntu 22.04.3
 

Best Regards,
Moosa

**Comment by avishai987** [comment]
> Dear @avishai987
> 
> Sorry to hear that.
> 
> I tried to install rbioapi on the WSL Ubuntu on my laptop a moment ago, and it installed just fine. Furthermore, I triggered [this GitHub action](https://github.com/moosa-r/rbioapi/actions/runs/7477401421) that installs the package and performs checks on several R versions and operation systems (please see below). All tests were passed successfully as you can see in the [action logs](https://github.com/moosa-r/rbioapi/actions/runs/7477401421).
> 
> R version 4.3.2 on macOS 12.7.2 R version 4.3.2 on Windows Server 2022 10.0.20348 R version 3.6.3 on Windows Server 2022 10.0.20348 R version 4.1.3 on Windows Server 2022 10.0.20348 R version 4.3.2 on Ubuntu 22.04.3 R Under development (unstable) (2024-01-09 r85796) on Ubuntu 22.04.3 R version 4.2.3 on Ubuntu 22.04.3 R version 4.1.3 on Ubuntu 22.04.3 R version 4.0.5 on Ubuntu 22.04.3 R version 3.6.3 on Ubuntu 22.04.3
> 
> Best Regards, Moosa

Hi Moosa,
Yes, you are right, apparently, the problem was in my .Rprofile file.
Thanks!
