### ISSUE TITLE
Support for background gene list in EnrichR

### ISSUE THREAD

**Issue by sam-israel** [moosa-r/rbioapi#16]
The EnrichR API was updated to include support for background gene list.

https://maayanlab.cloud/Enrichr/help#api&q=4

Would it be possible to add this functionality to rbioapi?

Thank you

**Comment by moosa-r** [comment]
Dear @sam-israel

Thank you for creating this issue.

I was planning to implement this update for a fairly long time. However, I have been extremely busy since the past few months. I will try my best to add it in the near future and will get back to you when this is done.

Best,
Moosa

**Comment by moosa-r** [comment]
Hello @sam-israel,

 I finally found time to implement providing a background gene list for Enrichr.
 
I'll update the CRAN version after the New Year's holidays. For now, you can use this feature by installing the latest version of rbioapi from the GitHub repository:
 
```
 install.packages("remotes")
remotes::install_github("moosa-r/rbioapi")
```

**Comment by sam-israel** [comment]
Thank you!
