### ISSUE TITLE
Internal Error: Failed to parse the server's response. This is probably because the server has changed the response format. Please report this bug to us: 

### ISSUE THREAD

**Issue by AlannaGSpiteri** [moosa-r/rbioapi#17]
> rba_reactome_event_hierarchy("Mus musculus")
Retrieving the complete events hierarchy tree of the Specie Mus musculus.
Error in .rba_skeleton(input_call) : 
  Internal Error: Failed to parse the server's response. This is probably because the server has changed the response format. Please report this bug to us: 
 Error : parse error: trailing garbage
          ]}]}]}]}]}]}]}]}]}]}]}]}]}]}]{"code":500,"reason":"INTERNAL_
                     (right here) ------^

**Comment by moosa-r** [comment]
Hello,

Thank you for submitting this error.

This is due to internal errors from Reactome API. I've submitted an error report on their website (rbioapi is just an unofficial wrapper for API services). As a workaround, there seems to be no problem if you query with mouse taxa ID:

````
rba_reactome_event_hierarchy("10090")
````
