### ISSUE TITLE
Panther API update

### ISSUE THREAD

**Issue by alexankc** [moosa-r/rbioapi#2]
Hi,

I have started using your tool and realized there are some differences between the results from the _rba_panther_enrich_ function and the Panther website (including their version of the Panther API).  

It would be great if you could incorporate these updates in rbioapi.

Cheers,
Alex

**Comment by moosa-r** [comment]
Dear Alex

Thank you for creating this issue. I have checked and it seems that rbioapi is up to date with PANTHER's API services. 

I've also run the example in [rba_panther_enrich](https://rbioapi.moosa-r.com/reference/rba_panther_enrich.html) function and the results are identical when the same parameters are used in the PANTHER website:


```r
rba_panther_enrich(
genes = c("p53", "BRCA1", "cdk2", "Q99835", "CDC42",  "CDK1", "KIF23", "PLK1", "RAC2", "RACGAP1"),
organism = 9606,
annot_dataset = "GO:0008150",
cutoff = 0.01
)
```


![image](https://user-images.githubusercontent.com/62205735/154519094-94bbe105-37c5-41be-9dd6-bd1906cc40e1.png)

Could you please provide me the code snippet that produced inconsistent results so I could be of more help?

Best,
Moosa

**Comment by alexankc** [comment]
Thank you for your reply Moosa!

I just realized there was something wrong with my input in my script, so that's why there was some difference. There is no issue with PANTHER.

Thank you for taking the time to consider this.

Best,
Alexandros
