### ISSUE TITLE
P-values and FDRs inconsistent

### ISSUE THREAD

**Issue by iasiimwe** [moosa-r/rbioapi#5]
Thanks for this beneficial tool. However, when I use the rba_reactome_analysis(input = genes_list, species = "Homo sapiens") function, I consistently obtain p-values and FDRs that are different from the results I obtain when I run the analysis directly on the site (https://reactome.org/PathwayBrowser/#/DTAB=AN). This also affects the most significant pathways as they are sorted by p-value.

**Comment by moosa-r** [comment]
Hi.
This is strange, since rbioapi uses the same API endpoints of Reactome analysis services without any modification or re-computations. Could you please send a reproducible example including the input genes?

**Comment by iasiimwe** [comment]
library(rbioapi)
# Example genes
genes <- c("A2M", "ABCB4")

# Analyze all genes
analyzed_all_genes <- rba_reactome_analysis(input = genes, species = "Homo sapiens")

# Download a full pdf report
  file_name <- "example"
  rba_reactome_analysis_pdf(token = analyzed_all_genes$summary$token,
                            species = 9606,
                            save_to = paste0(file_name, ".pdf")) 
[example.pdf](https://github.com/moosa-r/rbioapi/files/9654096/example.pdf)

# Results
# |            |Entities                |Reactions  |
# |Pathway name|found|ratio|p-value|FDR*|found|ratio|
# |Defective ABCB4 causes PFIC3, ICP3  and GBD1| 1/4 | 2.63e-04 | 0.002 | 0.019 | 1/1 | 7.10e-05
  
# If you analyze the same genes on the site (follow https://reactome.org/PathwayBrowser/#/DTAB=AN&ANALYSIS=MjAyMjA5MjcwOTI0NThfNjkzMg%253D%253D
# to download the results), the top pathway is different:
[report.pdf](https://github.com/moosa-r/rbioapi/files/9654100/report.pdf)

  # |            |Entities                |Reactions  |
  # |Pathway name|found|ratio|p-value|FDR*|found|ratio|
  # |ABC-family proteins mediated transport | 2/124 | 0.008 | 3.96e-04 | 0.005 | 2/27 | 0.002

**Comment by iasiimwe** [comment]
```{r Example}
library(rbioapi)

# Example genes
genes <- c("A2M", "ABCB4")

# Analyze all genes
analyzed_all_genes <- rba_reactome_analysis(input = genes, species = "Homo sapiens")

# Download a full pdf report
  file_name <- "example"
  rba_reactome_analysis_pdf(token = analyzed_all_genes$summary$token,
                            species = 9606,
                            save_to = paste0(file_name, ".pdf"))
```
Results
|                        |Entities                |Reactions  |
|Pathway name|found|ratio|p-value|FDR*|found|ratio|
|Defective ABCB4 causes PFIC3, ICP3  and GBD1| 1/4 | 2.63e-04 | 0.002 | 0.019 | 1/1 | 7.10e-05
[example.pdf](https://github.com/moosa-r/rbioapi/files/9654151/example.pdf)


If you analyze the same genes on the site (follow https://reactome.org/PathwayBrowser/#/DTAB=AN&ANALYSIS=MjAyMjA5MjcwOTI0NThfNjkzMg%253D%253D
to download the results, the top pathway is different:
|            |Entities                |Reactions  |
|Pathway name|found|ratio|p-value|FDR*|found|ratio|
|ABC-family proteins mediated transport | 2/124 | 0.008 | 3.96e-04 | 0.005 | 2/27 | 0.002
[report.pdf](https://github.com/moosa-r/rbioapi/files/9654147/report.pdf)

**Comment by moosa-r** [comment]
Thank you for the input. I will look into it as soon as possible.

**Comment by moosa-r** [comment]
Dear @iasiimwe 

I'm truly sorry for the very late response.

As I am checking, the results are identical. The issue was that one of the default parameters was different Reactome Analysis web portal , I've [changed the rbioapi function's defaults](https://github.com/moosa-r/rbioapi/commit/2650a791582becf2d9de815d30431d3e79e0d8bb) to be consistent with the web portal. 

Thank you for reporting the issue.

```
x <- rbioapi::rba_reactome_analysis(input = c("A2M", "ABCB4"),
                               projection = TRUE,
                               interactors = FALSE,
                               resource = "TOTAL",
                               include_disease = TRUE,
                               sort_by = "ENTITIES_FDR")

x$pathways[,c("name","entities.pValue", "entities.fdr")]


1             Defective ABCB4 causes PFIC3, ICP3 and GBD1    0.0010533938  0.005266969
2                  ABC-family proteins mediated transport    0.0003958576  0.005266969
3                         PPARA activates gene expression    0.0007849019  0.005266969
4             Regulation of lipid metabolism by PPARalpha    0.0008028031  0.005266969
5                            Transport of small molecules    0.0009960884  0.005266969
6                        Abacavir transmembrane transport    0.0023689655  0.009475862
7                                            HDL assembly    0.0047337195  0.013664383
8                                       Atorvastatin ADME    0.0052586490  0.013664383
9              Intrinsic Pathway of Fibrin Clot Formation    0.0068321915  0.013664383
10                            Plasma lipoprotein assembly    0.0078801823  0.015760365
11                                          Abacavir ADME    0.0084038665  0.016807733
12                                        Prednisone ADME    0.0089273434  0.017854687
13            Formation of Fibrin Clot (Clotting Cascade)    0.0112804250  0.022560850
14                              ABC transporter disorders    0.0258278115  0.025827811
15 Plasma lipoprotein assembly, remodeling, and clearance    0.0266025780  0.026602578
16                                Platelet degranulation     0.0366325481  0.036632548
17           Response to elevated platelet cytosolic Ca2+    0.0384245615  0.038424561
18                Degradation of the extracellular matrix    0.0384245615  0.038424561
19                                   Metabolism of lipids    0.0477578787  0.047757879
20                                              Drug ADME    0.0592310716  0.059231072
21                Disorders of transmembrane transporters    0.0717511119  0.071751112
22         Platelet activation, signaling and aggregation    0.0749857506  0.074985751
23                      Extracellular matrix organization    0.0836523795  0.083652380
24                                             Hemostasis    0.1953534083  0.195353408
25                                             Metabolism    0.2446414047  0.244641405
26                                                Disease    0.5276558286  0.527655829
```

![web](https://user-images.githubusercontent.com/62205735/196971577-1970ba58-1068-4911-b55c-103bd180b6c5.jpg)

Please note that the differences in the order of the first 4 rows are because they have equal FDR values and the results are sorted by FDR. Nevertheless, The p values and other values are identical.
