### ISSUE TITLE
Database Connection

### ISSUE THREAD

**Issue by klpara** [moosa-r/rbioapi#6]
Hello,

I am trying to access PANTHER but the database is not responding, I restarted the R session but still having trouble accessing it. Is there some way to fix this?

Thank you!

> rba_connection_test(print_output=TRUE)
Checking Your connection to the Databases currently supported by rbioapi:
--->>> Internet :
+++ Connected to the Internet.
--->>> Enrichr :
+++ The server is responding.
--->>> Ensembl :
+++ The server is responding.
--->>> JASPAR :
+++ The server is responding.
--->>> miEAA :
+++ The server is responding.
--->>> PANTHER :
!!! failed with error:
 Error in curl::curl_fetch_memory(url, handle = handle) : 
  Recv failure: Connection was reset
--->>> Reactome Content Service :
+++ The server is responding.
--->>> Reactome Analysis Service :
+++ The server is responding.
--->>> STRING :
+++ The server is responding.
--->>> UniProt :
+++ The server is responding.

> rba_options()
  rbioapi_option current_value            allowed_value
1    diagnostics         FALSE     Logical (TRUE/FALSE)
2       dir_name       rbioapi                Character
3       progress         FALSE     Logical (TRUE/FALSE)
4      retry_max             1   Numeric (0 or greater)
5     retry_wait            10   Numeric (0 or greater)
6      save_file         FALSE     Logical (TRUE/FALSE)
7     skip_error         FALSE     Logical (TRUE/FALSE)
8        timeout            90 Numeric (0.1 or greater)
9        verbose          TRUE     Logical (TRUE/FALSE

**Comment by moosa-r** [comment]
Dear @klpara 

This is a network-related issue. Either PANTHER was down when you tried this or you/ your network is blocked by PANTHER.
Currently, PANTHER [seems to be down](https://downforeveryoneorjustme.com/pantherdb.org). I will check again after the website is up.

**Comment by moosa-r** [comment]
PANTHER is up again and rbioapi is communication with the server without issues. Feel free to re-open the issue if you have other problems.

```
rbioapi::rba_connection_test()
```
```
Checking Your connection to the Databases currently supported by rbioapi:
--->>> Internet :
+++ Connected to the Internet.
--->>> Enrichr :
+++ The server is responding.
--->>> Ensembl :
+++ The server is responding.
--->>> JASPAR :
+++ The server is responding.
--->>> miEAA :
+++ The server is responding.
--->>> PANTHER :
+++ The server is responding.
--->>> Reactome Content Service :
+++ The server is responding.
--->>> Reactome Analysis Service :
+++ The server is responding.
--->>> STRING :
+++ The server is responding.
--->>> UniProt :
+++ The server is responding.
```

As example:

```
rba_panther_enrich(genes = c("p53", "BRCA1", "cdk2", "Q99835", "CDC42",
        "CDK1", "KIF23", "PLK1", "RAC2", "RACGAP1"),
    organism = 9606, annot_dataset = "GO:0008150",
    cutoff = 0.01)
```

```
Performing over-representation enrichment analysis of 10 input genes of organism 9606 against GO:0008150 datasets.
$reference
$reference$organism
[1] "Homo sapiens"

$reference$mapped_count
[1] 20589

$reference$unmapped_count
[1] 0


$input_list
$input_list$organism
[1] "Homo sapiens"

$input_list$mapped_count
[1] 10

$input_list$mapped_id
 [1] "CDC42"   "RACGAP1" "cdk2"    "PLK1"    "RAC2"    "CDK1"    "KIF23"   "BRCA1"   "Q99835"  "p53"    

$input_list$unmapped_count
[1] 0


$result
   number_in_list fold_enrichment          fdr    expected number_in_reference       pValue plus_minus    term.id	term.label
1               8       23.036643 1.470311e-06 0.347272816                 715 9.376385e-11          + GO:0010564	regulation of cell cycle process
........


$search
$search$search_type
[1] "overrepresentation"


$tool_release_date
[1] 20221013

$enrichment_test_type
[1] "FISHER"

$annotDataSet
[1] "GO:0008150"

$annot_version_release_date
[1] "GO Ontology database DOI:  10.5281/zenodo.6799722 Released 2022-07-01"

$correction
[1] "FDR"
```

**Comment by klpara** [comment]
Thanks a lot!

Best,

Kathyani
________________________________
