### ISSUE TITLE
pulling hierarchy sort indices from Panther

### ISSUE THREAD

**Issue by AmelZulji** [moosa-r/rbioapi#7]
Thank you very much for the tool! Its great to have consistent access to a lot of resources.

Recently, Panther introduced sorting resulting GO terms based on the hierarchy, which is pretty helpful in my hands. Is there any way to retrieve that information? 

Regards,
Amel

**Comment by moosa-r** [comment]
Dear Amel,

I appreciate your interest. Unfortunately, I'm limited here to what PANTHER's API provides.
I checked again, but currently, this API endpoint returns only the term's names and IDs in the results.


Kind regards,
Moosa

**Comment by NanoCoreUSA** [comment]
Since it's been a while I was just wondering if the PANTHER API was ever updated to provide the hierarchy data? I find this tool very useful but having all the parent info in the results confounds interpretation due to the increase in redundancy.
